### ISSUE TITLE
Support for other Delimiter

### ISSUE THREAD

**Issue by lazywinadmin** [apetitjean/EZLog#5]
I think the default delimiter should be a tabular character and could be optionally specify by the user

Thoughts?

**Comment by apetitjean** [comment]
Indeed the user should be able to choose his delimiter. 

I'm not sure if the tabular character should be the default, at least not for me. I would prefer to use the default settings (Windows regional Settings) that is used by -UseCulture of ConvertTo-CSV. 
Now the question is how ConvertTo-CSV -UseCulture behave with PS Core? I mean from where the delimiter's value comes from.

**Comment by lazywinadmin** [comment]
Hum i did not know about UseCulture.
It seems that it is coming from

`(Get-Culture).TextInfo.ListSeparator`

I'm fine with the semi-colon and use the use the -Delimiter parameter with the CSV Cmdlets if needed :-)

**Comment by apetitjean** [comment]
Hi FX!

I've just implemented in v1.6.0 a delimiter parameter that has to be defined (optionally) is combination with the header parameter.

ConvertFrom-EZLog is smart enough to detect the delimiter when importing a log file.

Sorry for the delay ;-)

Arnaud
